### ISSUE TITLE
ManualMenuView fails if User doesn't have a profile record

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#112]
`ManualMenuView` (path `/fpiweb/manualmenu/`) fails if the current user doesn't have an associated `Profile` record.

**Comment by jocassid** [comment]
I fixed this by creating a `Profile.get_profile_for_user` which will create a `Profile` record if one doesn't already exist.  Please assign this to me.

**Comment by deeppunster** [comment]
Thanks John for both finding the source of this bug and offering a fix.
