### ISSUE TITLE
Replace Box, Pallet, and Activity fields loc_row, loc_bin, and loc_tier with single foreign key to location.

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#118]
Reduce duplication of data.  Allow potential of creating a location w/out row,bin,tier (i.e. "pallet assembly location A", "In the broom closet", etc).

**Comment by deeppunster** [comment]
I looked at the PL submitted for this and found a few discrepancies.  

* The json data has the row, bin, and tier removed, but the location field is always null -- which makes the data invalid.  ( for example, Box.json )
* There are two migration files - 0020 and 0021 included in the PL.  However, the dev branch of the main repository already has files with those numbers.  Shouldn't these migrations have higher numbers?  (Also, wouldn't it help others understand if they were squashed and given a helpful name?)
* Wouldn't make more sense to add location to the various tables in one PL, run a conversion utility to populate the data from row/bin/tier, then remove the fields at a later date?

**Comment by jocassid** [comment]
restore row, bin and tier fields in activity table.  Use the code values from each respective table, do not store foreign keys.  The reason is if referenced record is edited or deleted we want to retain historical data.

Convert DateTime fields in Activity to Dates.  Resolution at Date level is sufficient.  Higher resolution is neither required or desired (add a comment to this effect).

The dev branch has migrations with numbers that conflict with the migrations I created in this branch.  rebase and create new migrations with non-conflicting number

Test and fix scanner view (getting ride of Box row, bin, tier) broke it.

**Comment by deeppunster** [comment]
Done
