### ISSUE TITLE
git rid of FIELD_max_length variables.

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#119]
You ain't going to need it.  There's ways of getting at the meta data of field.  Validation against max length of field happens automatically.   I think there's somewhere we're referencing one of the variables for `help_text` somewhere, but we can probably pull `help_text` from field data if needed so we might want to revisit the decision to create variables for the `help_text` values.

**Comment by deeppunster** [comment]
Agree.  Let's document this and how to get at the meta data so others will understand as well.

**Comment by jocassid** [comment]
I take it back.  Getting at metadata isn't straightforward.
