### ISSUE TITLE
Find a place for some useful git commands for new contributors.

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#12]
Here's a couple of things we might want to document:

How to clone your fork onto your computer
`git clone https://github.com/USERNAMEFood-Pantry-Inventory.git`

How to add the main w-a-r-m-inventory-system/Food-Pantry-Inventory repository on your computer so you can pull changes from the main repo into your fork.
`git remote add upstream https://github.com/w-a-r-m-inventory-system/Food-Pantry-Inventory.git`

**Comment by deeppunster** [comment]
Hi John,

Please look at the document “Git Guidelines.rst” in the docs folder. 
If this seems inadequate for describing how to do these activities, 
please help us improve this document.

Thanks,
Travis

**Comment by jocassid** [comment]
Setup instructions for PyCharm  include instructions for setting up the main repository as a remote repository.
