### ISSUE TITLE
Dump full Activity table to a CSV file on the local computer.

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#128]
An administrative user should be able to select a menu pick and dump the full Activity table to the local computer as a CSV file.

**Comment by jocassid** [comment]
No filtering by date range (at lease for now)

All fields from activity table (we'll be putting back row, bin, and tierl) except for the primary key.

**Comment by jocassid** [comment]
I have view in changes for #118 need to restrict this to admin users.

**Comment by deeppunster** [comment]
Assigning to John.  John has already added code to the project to dump the activity table to a csv file.  Perhaps allowing administrator-only access does not require more code, just a brief description of how to create a role for this and assign the role to administrators in  the Django admin area.

**Comment by deeppunster** [comment]
done
