### ISSUE TITLE
Build Pallet Screen: Navigation and Pallet records

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#139]
- [x] Replace "Back to test_scan page" with a link back to `/fpiweb/` homepage.
- [ ] Display User's current pallet record.  And update box.pallet.
- [x] In the confirmation page add a link back to the homepage.
- [ ] If box is full prompt user with option to empty or cancel scan

**Comment by deeppunster** [comment]
- Display user's current pallet record will be handled by a general update to every page's header.
- Updating the "box.pallet" was meant to be the pallet ID in the Profile record.  This will be handled by issue #190. 
- If box is full... This is not needed. We will presume that the box was not recorded as emptied and is being refilled again.  This is reflected in the records written to the Activity Table.
