### ISSUE TITLE
Implement Move Pallet

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#161]
1. Enter "Move from" location using row, bin, and tier `<select>` elements.  Upon submit display form with errors if the location doesn't exist or there are no boxes at that location.
2. If the "Move from" location exists and has boxes display row, bin, and tier `<select>` elements to select the "Move to" Location.  This page will also list the boxes at the "Move from" location.  Upon submit display form with errors if the "Move to" location doesn't exist
3. If there are boxes at the "Move to" location let the user know that and give them an option go back and select another location or continue.  (continuing is merging pallets and that's ok)
4. Generic "N boxes moved from A to B" message.
5. Use `BoxManagementClass.pallet_finish` to update the database.

**Comment by deeppunster** [comment]
Verify that the code sets appropriate pallet status before passing pallet to BoxManagement
