### ISSUE TITLE
Provide way for anyone to view/search the Product Examples table

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#206]
- This view/search should be a “full text” search of the Product Examples Table.  E.g. a search for “peas” should show all records that have peas somewhere in the description including black eyed peas, green peas, young peas and peasant (if exists).
- Each entry found should list the product that is appropriate for it so that the user can select the proper product.
- This is particularly important for product examples that could be in in more than one product.
  - Beef stew could be in either meat or soup.  
  - It is up to the food pantry to decide.

This view or search should be available whenever a product is being selected.  How to accomplish this is up to the implementor.

**Comment by deeppunster** [comment]
This view search should be available to any logged in user.

**Comment by jocassid** [comment]
search by product_example_name (use __icontains), show products.

**Comment by deeppunster** [comment]
Support for product examples has now been added to the system.
