### ISSUE TITLE
Staff Permissions - can:

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#209]
- Can manage all user data:
— boxes
— durable data (e.g. product, box type, location, etc.)
— constraints
- Can print QR labels
- Can dump activity data
- Can add user information - including permission level and initial password
- Can change user permission level (volunteer -> staff, staff -> volunteer)
- Can block a user’s access
- Everything that a volunteer can do

**Comment by jocassid** [comment]
Need to setup permissions when the following maintenance views are in place

- [ ] System User
- [ ] Product Category
- [ ] Product Name
- [ ] Product Example
- [ ] Rebuild Location Table (I'd recommend having a script that is run as part of the install process.
- [ ] Manual Location Table Maintenance

**Comment by deeppunster** [comment]
A quick comment about one of the items in the list. Rebuild Location Table already has a menu item reserved for it in the System Maintenance menu.  The code used for this menu item could be written so that it could be used for the script as well.
