### ISSUE TITLE
Eliminate the standalone QR print program

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#211]
- Reason - it needs access to the database to skip box numbers already in use.  However, when the live database is is in production, providing secure access to the database will be more difficult than just using the menu pick.

**Comment by jocassid** [comment]
Got an "'QRCodePrinter' object has no attribute 'label_locations'" error.

**Comment by deeppunster** [comment]
Did this error occur when attempting to run via the "Print Labels" menu pick?  If so, it is not functional until someone can rewrite the code.  Currently only the program in StandaloneTools works correctly.

**Comment by jocassid** [comment]
Yeah, that error happens when accessing http://127.0.0.1:8000/fpiweb/print_labels/.  I understand that page is under construction.

**Comment by deeppunster** [comment]
This issue was addressed by PR #277 and has been closed.
