### ISSUE TITLE
Check Status of Box

### ISSUE THREAD

**Issue by babarehner** [w-a-r-m-inventory-system/Food-Pantry-Inventory#230]
Under Manual Box and Pallet Management -> Manage an Individual Box Manually -> Check the Status of a Box when you enter a **box numbe**r that is not currently in the database this raises an exception. The exception message is "**_AttributeError at /fpiweb/manual_box_status/  'ExtantBoxNumberForm' object has no attribute 'get'._** When you enter a **box number** that is present in the database the web page progresses normally.

**Comment by deeppunster** [comment]
Fixed by issue #257.
