### ISSUE TITLE
Build login page

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#25]

**Comment by jocassid** [comment]
I've started work on a login page.  Can you assign this issue to me?

**Comment by snelzing** [comment]
As you wish. Thanks for your help. Will you be at the meeting tomorrow or the Dojo? If you are willing, it would be helpful if you could walk us through how to make a login page. Even just commenting though could be helpful as well. 
BTW thanks for the book, I have found it immensely helpful.
Sne 
  

    On Monday, April 1, 2019, 9:53:14 PM MDT, John Cassidy <notifications@github.com> wrote:  
 
 
I've started work on a login page. Can you assign this issue to me?

**Comment by deeppunster** [comment]
Hi John,  could you add instructions (preferably under docs) as to what needs to be added to the other web pages so:

- The web page does not allow a user to see or make any changes until they have been authenticated
- Redirects the user to the login page for authentication
- Returns the user to the original page after after authentication

Thanks!

**Comment by deeppunster** [comment]
John added code for the login page in PL#29.  Subsequent changes by John and others added the logout page and the LoginRequiredMixin to require/redirect to the login page as appropriate.
