### ISSUE TITLE
Add ability for a user to change their own password

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#259]
Currently the system allows only admins to set or change passwords.  There is a menu pick for changing the current user's password, but it just goes to the about screen.

it should require the user to enter the usual info: current password, new password twice.  If the new password is accepted, the system should acknowledge that to the user.  If the new password is rejected, the system should allow them to pick a different new password.

Guidance should be provided in the initial screen as to what is or is not allowed for a password.

Hopefully libraries like zxcvbn-python can be used to provide sensible password checking.
Perhaps a library that will provide an on-screen strength meter can be added.  If not now later.

**Comment by deeppunster** [comment]
Duplicate of issue #176.

**Comment by jocassid** [comment]
Django has a built-in password validator `django.contrib.auth.password_validation.CommonPasswordValidator` (see `AUTH_PASSWORD_VALIDATORS` in your settings file).  I pushed a branch for #176 to my github repo with the work in progress)

**Comment by deeppunster** [comment]
This issue was addressed by PR #290 and is now closed.
