### ISSUE TITLE
Read the Docs is not building using Python 3.8

### ISSUE THREAD

**Issue by jallman112** [w-a-r-m-inventory-system/Food-Pantry-Inventory#285]
**Describe the bug**
Read the Docs is not building using Python 3.8.

**To Reproduce**
See the error log here: https://readthedocs.org/projects/food-pantry-inventory/builds/12606778/

**Expected behavior**

**Screenshots**
Read the Docs is creating the virtual environment using 3.7:
![image](https://user-images.githubusercontent.com/3280981/103016755-8f3f0f80-4510-11eb-9ae6-d57abcc6939b.png)

Pip install fails due to 3.8 project requirement:
![image](https://user-images.githubusercontent.com/3280981/103016815-abdb4780-4510-11eb-982f-9866bf68ce06.png)

**Comment by jallman112** [comment]
The way to specify the Python version for Read the Docs builds is to add a configuration file (.readthedocs.yml) to the project root.  PR #286 introduces this configuration file to the dev branch.

RTD config file documentation is here: https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by deeppunster** [comment]
This issue has been resolved by Jeff Allman with PR #286.  Thanks, Jeff!
