### ISSUE TITLE
WordTrekSolver left in

### ISSUE THREAD

**Issue by snelzing** [w-a-r-m-inventory-system/Food-Pantry-Inventory#33]
"__author__ = 'Travis Risner'
__project__ = "WordTrekSolver"
__creation_date__ = "04/01/2019""

I think this is left in from a past project. 

Probably a temporary placeholder, I just wanted to practice making an issue and set a reminder.

**Comment by deeppunster** [comment]
Yes, it is left over from a different project.  I have submitted pull request #34 to fix this for the existing modules.  If this creeps in again, feel free to update it on the spot.  You can bash me on the side of the head later.
