### ISSUE TITLE
Build Add Inventory screen

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#39]
Please assign to @jocassid

**Comment by deeppunster** [comment]
See T7 for details and specifications in the Outstanding Tasks document located in the ./docs/source directory.

**Comment by jocassid** [comment]
* If the box number is not already in the box table, add this box entry to the table when saved.
* If the box number is already in the box table and is empty (no product), prepopulate the box type from the box record found.
* If the box type is not prepopulated, default to the "Evans" box type.
* If the box number is already in the box table and is not empty (some product is currently in the record, show an error message and allow the user to empty the box before continuing.
* Validate the fields as needed (product, expiration year),
* Allow the user to specify beginning and ending months if the user desires. Entering a month in either field requires that the other must be filled. However, allow the user the option to blank out both fields, if desired.
* When saved, create a new activity record and fill in these fields from the new box record just saved.
        box number
        box type
        date_filled
        exp_month_start (use 1 unless otherwise specified in the box record)
        exp_year
        loc_row
        loc_bin
        loc_tier
        product_cat_name (string not product category id)
        prod_name (string not product id)
        quantity (from box type record)

**Comment by jocassid** [comment]
Closing this.  Create new issues for further modifications

**Comment by jocassid** [comment]
Closing this. Create new issues for further modifications
