### ISSUE TITLE
Box Type Table - build ACID screens

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#42]
Build screens to list, add, change, and delete box types.

- Include requirement that the user must be logged in before  these screens can be used.
- Add link to index page to get to  the list screen.

**Comment by deeppunster** [comment]
See T4 for details and specifications in the Outstanding Tasks document located in the ./docs/source directory.

**Comment by jocassid** [comment]
From Outstanding Tasks document ...

Build web pages that will allow an authorized user to add, change and delete box type entries. Deleting a box type will not be permitted if there are any product entries referencing this box type.

**Comment by jocassid** [comment]
This could be done using the admin screens.  Create a `BoxTypeAdmin` class and register it in `fpiweb/admin.py`.  There are a couple examples in the `admin.py` or you can check the documentation [here](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#modeladmin-objects).  In addition to `list_display` you might want to consider other [ModelAdmin options](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#modeladmin-options).  The Django permission system provides a lot of granularity to control who can do what.

**Comment by deeppunster** [comment]
This issue was addressed by PR #289 and can now be closed.
