### ISSUE TITLE
Modify base.html template to uses static files rather than CDN urls

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#53]
When any page using base.html template loads you'll notice requests going to urls outside our app (Content Delivery Network) sites.  Change template to have it load file from our static directory.  This may require adding JQuery ... min.js files to the project.

**Comment by deeppunster** [comment]
See T3 for details and specifications in the Outstanding Tasks document located in the ./docs/source directory.

**Comment by Melon-Bread** [comment]
I am off this weekend. I will get a PR done to solve this.

**Comment by deeppunster** [comment]
Mike Rehner submitted pull request #155 that addressed this issue.
