### ISSUE TITLE
QR Label print program needed

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#55]
We need to add a program to print a sheet of QR codes on Avery llabels (or equivalent).  More documentation will be added in the next few days.

We may want to consider printing to a dedicated label printer such as a Dymo printer.

**Comment by deeppunster** [comment]
See T1 for details and specifications in the Outstanding Tasks document located in the ./docs/source directory.

**Comment by jocassid** [comment]
I just noticed that the Django docs have a page on generating PDF output located [here](https://docs.djangoproject.com/en/2.2/howto/outputting-pdf/)

**Comment by deeppunster** [comment]
The CLI version of the program is complete and ready to test.  I will work on a GUI front end when I get a chance.

**Comment by deeppunster** [comment]
Closing this issue since the CLI program is complete and issue #71 covers writing the GUI version.
