### ISSUE TITLE
Scan a QR code

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#57]
Scan a QR code and present the appropriate screen.

See T9 in the Outstanding Tasks document located in the /docs/source directory.

**Comment by jocassid** [comment]
From Outstanding Tasks document:

Build a screen that is presented when a QR code has been scanned.  Based on
what is found or not found in the database, switch to an appropriate screen.

Box Record Status | Action Taken
----------------------- | ----------------
No box record | Present new box screen
Box record empty | Present new box screen
Box record filled | Present empty or move box screen


..  table::  Box Record Status and Action Taken
    :widths: auto
    :align: left

=================  ============
Box Record Status  Action Taken
=================  ============
No box record      Present new box screen
Box record empty   Present new box screen
Box record filled  Present empty or move box screen
=================  ============

**Comment by jocassid** [comment]
Please add enhancement label to this and assign it to me

**Comment by jocassid** [comment]
- [ ] Change name of Add Box screen to new box (change viewname, url name, and the title on the page)
- [ ] Make the Visible box number-read only (label has been pre-printed and added)
- [ ] Remove Box.print_box_number_label field.

**Comment by jocassid** [comment]
I think we can close this one and figure out what subsequent screens should be.

**Comment by deeppunster** [comment]
Closing per John's request above.
