### ISSUE TITLE
Populate Box.quantity when Box record is created.

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#64]
- [x] When a Box record is created.  Set the Box.quantity to the value specified by Box type.  
- [x] Remove the Quantity field from the screens (field is left in place for future reference).  
- [ ] Copy quantity value from Box to Activity record when Box is empty (Dependency on #67).

**Comment by jocassid** [comment]
mark as bug, milestone 1, assign to me.

**Comment by jocassid** [comment]
@deeppunster, looks like you have some tests that are checking this field.  Can this be closed?

**Comment by deeppunster** [comment]
I believe this bug has been fixed.  Closing issue.
