### ISSUE TITLE
Empty Box functionality

### ISSUE THREAD

**Issue by jocassid** [w-a-r-m-inventory-system/Food-Pantry-Inventory#67]
Need description of how this is to work.  Label as enhancement and milestone 1

**Comment by deeppunster** [comment]
An empty box is either in the inventory system or not.  

- Empty box not in inventory
    - It needs a QR code affixed so it is ready to add to inventory.
    - It will probably not be entered into the inventory system until the box is physically filled with product and is ready to be put at a location.
    - When the QR code is scanned for the first time, a box type will need to be chosen before the product and expiration year are selected.
-  Empty box already in inventory
    - The box is categorized as empty because it has not product, expiration or location associated with it.

**Comment by deeppunster** [comment]
The pallet box code has been modified so a box record is empty (no, product, location, or expiration date) or filled (has all three fields filled in..  Further, the code in BoxManagement will not allow a box to be filled without all needed information.
